[package]
name = "tg-echo"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
tg-flows = "0.2.1"
tokio = { version = "1.28.1", features = ["macros", "rt"] }
