[package]
name = "slack-echo"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
dotenv = "0.15.0"
flowsnet-platform-sdk = "0.1.5"
log = "0.4.19"
slack-flows = "0.3.0"
tokio = { version = "1.28.1", features = ["macros", "rt"] }
