[package]
name = "slack-echo"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
slack-flows = "0.3.0"
tokio = { version = "1.28.1", features = ["macros", "rt"] }
