[package]
name = "discord-echo"
version = "0.1.0"
edition = "2021"

[dependencies]
discord-flows = "0.4.0"
dotenv = "0.15.0"
flowsnet-platform-sdk = "0.1.5"
log = "0.4.19"
serde_json = "1.0.96"
tokio_wasi = { version = "1.25.2", features = ["macros", "rt"] }
